# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[custom.jj]
command = """
jj log --revisions 'heads(::@ & bookmarks())' --no-graph --ignore-working-copy --color always --limit 1 --template '
  separate(" ",
    "ğŸ¥‹",
    change_id.shortest(4),
    bookmarks,
    "|",
    concat(
      if(conflict, "ğŸ’¥ conflict"),
      if(divergent, "ğŸš§ divergent"),
      if(hidden, "ğŸ‘» hidden"),
      if(immutable, "ğŸ”’ immutable"),
      if(!(conflict || divergent || hidden || immutable), "âœ…", "")
    ) ++ raw_escape_sequence("\\x1b[0m"),
  )
'
"""
detect_folders = ['.jj']
# when = "git-change"
# style = "fg:red"
# prefix = ""
# suffix = " "
